### ISSUE TITLE
ERROR: Attempt to execute unknown function

### ISSUE THREAD

**Issue by angstsmurf** [DangarStu/JACL#17] opened 2023-01-25 07:34 UTC
I get weird errors in _The Unholy Grail_ with this version of JACL, which breaks my walkthrough script.
For example, at the very start:
```
>W
(The pool)
>N
(The control centre)
>TURN OFF LIGHT
ERROR: Attempt to execute unknown function “+turn_off”.
```
I get similar errors from other commands.
With the old version of the interpreter (209), this works and gives 10 points.
```
>TURN OFF LIGHT
You flick the light switch into the off position causing the main fluorescent light to go out.

Lisa is here, standing close by.

> close blinds
You reach over the control panel and turn the rod until the blinds close.

The control centre
With the main light off and the blinds closed, only the dim glow of the emergency lighting coupled with the many coloured and flashing indicator lights allows you to see. The shadowy form of the chair stands before the control panel as always.

Lisa is here, standing close by.

> examine screen
Two perpendicular fine white lines form a large cross hair on the screen. Markings along both the X and Y axes indicate longitude and latitude to within point zero one of an arc second.

With the current low level of lighting, you can just make out the rapidly fading afterimage of an unusually large blob at precisely -171deg14'02.30" longitude and -23deg34'86.34" latitude.

Watching you intently, Lisa points to the screen. "It's a whale, we get a lot of them out here."

[YOUR SCORE JUST WENT UP BY 10 POINTS]
```

**Comment by cspiegel** [comment] 2023-01-25 17:40
I can reproduce with Unholy Grail from the JACL 2.8.4 distribution, as well as 2.4.8.  With the version from Git master, it works properly.

Moreover, when I run the version from Comp 97, I get this:

```
ERROR: In line 5715, “hill” is already used as an object or location label.
ERROR: In line 7153, “counter” is already used as an integer constant label.
ERROR: 2 errors detected.
```
IFDB links to the 2.4.8 repository to download Unholy Grail, but this is _not_ the version I have in my local IF comp directory.  The version I have came from the official Comp 97 download, which is available here: https://www.ifarchive.org/indexes/if-archive/games/competition97/jacl/grail/

The JACL version included with Gargoyle is 2.9.0, and that's not compatible with the original comp entry, either.  Quick checks of 2.4.8 and 2.8.4 give the same errors.  The jacl.c file included with the comp entry runs it, but no other versions I've found do.

For Gargoyle, ideally the comp games would be playable (Curse of Eldor doesn't work, either).  Is that feasible?  Is there some form of versioning JACL uses/can use to ensure older games still play on newer interpreters?

**Comment by DangarStu** [comment] 2023-01-25 23:51
So these errors:

ERROR: In line 5715, “hill” is already used as an object or location label.
ERROR: In line 7153, “counter” is already used as an integer constant label.
ERROR: 2 errors detected.

Are indeed bugs in that version. The latest version of the interpreter identifies them while the earlier version just silently overwrote the first definition with the second. 

Is there a strong desire to get a version of the interpreter that will run the ifcomp97 release? 

The error:

ERROR: Attempt to execute unknown function “+turn_off”.

Is more a problem with the version of verbs.library that is being used and not so much an interpreter or game file error. When you first run .jacl file it will product a .j2 which you can think of a statically linked version with all the included libraries imbedded and whitespace removed to make execution faster. Which version are you running? Does it have #include statements at the end?

Stuart

**Comment by DangarStu** [comment] 2023-01-26 00:09
Oh, and to answer your question about versioning, the .j2 files write the version of the interpreter that created the file and the intepreter won't run it if it is a previous major version. I could maybe add a flag to surpress certain errors if it is an old game. Would that help?

**Comment by cspiegel** [comment] 2023-01-26 01:22
> The error:
> 
> ERROR: Attempt to execute unknown function “+turn_off”.
> 
> Is more a problem with the version of verbs.library that is being used and not so much an interpreter or game file error. When you first run .jacl file it will product a .j2 which you can think of a statically linked version with all the included libraries imbedded and whitespace removed to make execution faster. Which version are you running? Does it have #include statements at the end?

This occurs for me when I try to run the version from the [IFDB page](https://ifdb.org/viewgame?id=7p2rxk0e667yraf2) (in `jacl-2.4.8.zip`).  The end of the file looks like this:

```
#include "npc.library"
#include "utils.library"
#include "verbs.library"
```

> Oh, and to answer your question about versioning, the .j2 files write the version of the interpreter that created the file and the intepreter won't run it if it is a previous major version. I could maybe add a flag to surpress certain errors if it is an old game. Would that help?

I think that'd be useful, even if it does result in buggy behavior (as with the older version you mentioned, which silently overwrites duplicate data). If that buggy behavior was there in 1997, at least we're being honest in replicating it, and (in my opinion) that's better than not running it at all.

> Is there a strong desire to get a version of the interpreter that will run the ifcomp97 release?

Initially my answer to this was "yes".  But after looking over things, maybe that's not really a reasonable request.

The comp97 JACL runner (whose source was included with the game) can build and run the 97 Unholy Grail, but it won't run 96's Curse of Eldor.  It seems JACL was in a transitional state, with an appropriate interpreter bundled with each release. That is, there wasn't the expectation of a Gargoyle-like project which would try to run everything. If it were simple to support all releases, I'd strongly advocate for it, but I get the sense that the comp games were a product of the at-the-moment JACL development system.  Which is totally reasonable, just incompatible with Gargoyle.

What I _would_ ask, if JACL is to be supported in Gargoyle, is that the interpreter be able to run older games, excluding those which are already unplayable (i.e. the comp games).  If the current JACL interpreter (at whatever point in time) can only play recent games, it's not really a good fit for Gargoyle.  Which, again, is your prerogative and I wouldn't presume to ask you to do a boatload of work to support something that doesn't fit your project's goals.

I guess it feels something like this: the current JACL interpreter can run the 2008/2009 games from IFDB, and can at least load/start games from the 2.4.8 distribution, though with the bug @angstsmurf noted in Unholy Grail.  That seems a reasonable starting point: for JACL games written in 2008 onward (which I suppose is a proxy meant to say for games written for JACL 2.4.8 or later), newer JACL releases should support them.

I know this is asking a lot: basically, I'm requesting backward compatibility, and I admit I don't know how much work that'd be for you. It's just that if Gargoyle claims to support JACL, I'd like it to support as wide a variety of JACL games as possible.

**Comment by DangarStu** [comment] 2023-01-26 01:38
I've always really appreciated JACL being included in Gargoyle so I'm happy to do what I can to make it work with older games. I've downloaded the jacl-2.4.8.zip file so I'll take a look at what is going on in there. 

I think the best thing is to have some type of "permissive" flag that can be used by Gargoyle with people writing new games (ie, just me, still hoping to finish The Bloody Guns one day...) using it without the flag to get stricter code checking. 

For a bit of history, The Curse of Eldor was written in parallel with development of V1 of JACL so it was very much just a test of the engine. Mostly the engine is a superset of what is was in those days so it should be possible to make them run. If anything it will be a fun challenge. :)

Stu

**Comment by cspiegel** [comment] 2023-01-26 15:30
That's great, thank you!

If there's anything needed on the Gargoyle side as you're working on this, let me know.

**Comment by DangarStu** [comment] 2023-01-27 00:16
It has been interesting to look at the cause of these errors, I certainly didn't give any thought to backwards compatibility as the engine developed. Some things are simple, such as in The Curse of Eldor there is a 'variable' instead of an 'integer' as in those days there wasn't any such thing as a 'string' To fix that i've just made variable a synonym for integer. Other things are trickier though, but possibly doable. In the CoE days object and locations were two different things and could have the same name. Eventually everything became an object in the same namespace hence all the X is already used errors. A first I thought it was a bug in the game but it is actually valid code for that version of the engine. I could easily append _obj and _loc at creation, but changing all the places in the code that the objects and locations are referenced isn't so easy. This game also has an object called 'counter' and counter is now a reserved word in the interpreter. I could change that reserved word to something else though and updated the documentation.

The Intro Comp version of Bloody Guns was a processed .j2 file so I wrote a quick utility to decrypt it. That utility is commited in the GitHub repository now and shows me that the .j2 file was created with verison 2.0.2 of the interpreter.
The main problem I see with that game is that I used to have some generic attributes built into the interpreter such as FIRST as many actions give a different response the second time. ie, "You still can't lift the mountain." etc. Eventually I pulled them out of the interpreter to defined in the game and the libraries so TBG gives an FIRST unknown error. I can't see a huge problem with putting the ones that used to be predefined back in and removing their duplicated definitions from the libraries.

**Comment by DangarStu** [comment] 2023-01-27 01:47
I've created the branch "backwards-compatible" to start working on an interpreter that works with as many legacy games as possible.

**Comment by DangarStu** [comment] 2023-01-31 00:45
Work on the backwards-compatible branch is proving tricky but I'll press on with it. The language has changed a lot since those early days. I have updated the master branch to run the IntroComp version of The Bloody Guns though so that should now work, let me know if it gives you and problems.

With regards to the @angstsmurf was getting with The Unholy Grail, which game version was that? The game version in this repository seems to play fine with the interpreter version in this repository.

Stu

**Comment by DangarStu** [comment] 2023-01-31 00:57
I guess the other obvious thing to do is update places like IFDB with modern versions of the games that run with the current interpreter.

**Comment by angstsmurf** [comment] 2023-01-31 01:58
I got the game from here:
https://www.ifarchive.org/indexes/if-archive/games/jacl/

**Comment by DangarStu** [comment] 2023-01-31 02:45
Ah, thanks for that. I think the only real achievable outcome here is to make The Bloody Guns IntroComp version run (done) and then upload new versions of the other games to IF-DB and IF Archive. If does mean that the original IF Comp versions won't run, but maybe putting a link to the 2023 version on the page with a note saying that the old version is kept here for archival purposes but the modern versions are hosted elsewhere if you want to play it with Gargoyle. I could also change the interpreter so that it will detect that it can't run them and output a nice message rather than a series of errors.

Any thoughts?

Stu

**Comment by DangarStu** [comment] 2023-01-31 06:36
Okay, I might close this ticket as after looking at many other compatibility issues the original @angstsmurf reported error is now fixed. It's actually and error in the game but it was easy enough to change the interpreter to handle the error more gracefully so I may as well do it. Latest version in GitHub should run your walkthru of the IF Archive version of The Unholy Grail and the IntroComp version of The Bloody Guns.

Stu

**Comment by cspiegel** [comment] 2023-01-31 07:25
> Ah, thanks for that. I think the only real achievable outcome here is to make The Bloody Guns IntroComp version run (done) and then upload new versions of the other games to IF-DB and IF Archive. If does mean that the original IF Comp versions won't run, but maybe putting a link to the 2023 version on the page with a note saying that the old version is kept here for archival purposes but the modern versions are hosted elsewhere if you want to play it with Gargoyle. I could also change the interpreter so that it will detect that it can't run them and output a nice message rather than a series of errors.

This sounds like a very sensible approach.  I appreciate that the comp games are just too old to run on a modern version of JACL, and providing a specific error message is nicely pragmatic way to deal with it.

**Comment by DangarStu** [comment] 2023-01-31 22:03
Reported bug is in game file, workaround added to interpreter version 4.6.1

**Closed as completed by DangarStu** 2023-01-31 22:03 UTC
